# Generated by Django 3.2.10 on 2021-12-25 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20, verbose_name='場所')),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日')),
                ('today', models.CharField(max_length=150, verbose_name='今日の天気')),
                ('tomorrow', models.CharField(max_length=150, verbose_name='明日の天気')),
                ('today_high_temp', models.IntegerField(verbose_name='今日の最高気温')),
                ('today_low_temp', models.IntegerField(verbose_name='今日の最低気温')),
                ('tomorrow_high_temp', models.IntegerField(verbose_name='明日の最高気温')),
                ('tomorrow_low_temp', models.IntegerField(verbose_name='明日の最低気温')),
            ],
        ),
    ]
